### ISSUE TITLE
Nothing wrong

### ISSUE THREAD

**Issue by MrUnknownGamer** [Kalzedia/gmod-SmartLoader#1]
Just want to say I cant wait to see this

**Comment by domkalan** [comment]
We should have it done in the next couple of weeks or sooner.

**Comment by domkalan** [comment]
This is the basics of what we are trying to achieve here. As the readme states, the project is still under heavy development so many changes might take place. Do you have any feature request specifically? 
![img](http://i.imgur.com/2qSQaau.jpg)

**Comment by MrUnknownGamer** [comment]
A progress bar would be cool

**Comment by domkalan** [comment]
Yes, we are working on implementing a status bar.

**Comment by domkalan** [comment]
Expect some delays. We are having problems with our development server.
